apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: servicea-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-db
  labels:
    app: serviceA-db
    service: servicea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceA-db
      service: servicea
  template:
    metadata:
      labels:
        app: serviceA-db
        service: servicea
    spec:
      serviceAccountName: servicea-db
      volumes:
      - name: serviceA-db-volume
        persistentVolumeClaim:
          claimName: serviceA-db
      containers:
      - name: servicea-db-container
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: serviceA-db-volume
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "ssss"