apiVersion: v1
kind: Service
metadata:
  name: servicea-db
  labels:
    app: serviceA-db
    service: servicea
spec:
  selector:
    app: serviceA-db
    service: servicea
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP